# Generated by Django 5.0.3 on 2024-03-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_permissions'),
        ('first_app', '0003_alter_accessrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
